import { content } from '../content';

// Language-flavored `class TeachingAssistant { ... }` card for about-me.
export function buildSnippet(): string {
  const { name, course, email, session } = content;
  const officeHours = `${session.day} ${session.time} @ ${session.room}`;
  const lang = course.language.toLowerCase();

  switch (lang) {
    case 'python':
      return [
        'class TeachingAssistant:',
        '    def __init__(self):',
        `        self.name = "${name}"`,
        `        self.course = "${course.name}"`,
        `        self.semester = "${course.semester}"`,
        `        self.email = "${email}"`,
        '',
        '    def office_hours(self):',
        `        return "${officeHours}"`,
      ].join('\n');
    case 'java':
      return [
        'public class TeachingAssistant {',
        `    String name = "${name}";`,
        `    String course = "${course.name}";`,
        `    String semester = "${course.semester}";`,
        `    String email = "${email}";`,
        '',
        '    String officeHours() {',
        `        return "${officeHours}";`,
        '    }',
        '}',
      ].join('\n');
    case 'cpp':
    case 'c++':
      return [
        'class TeachingAssistant {',
        'public:',
        `    std::string name = "${name}";`,
        `    std::string course = "${course.name}";`,
        `    std::string semester = "${course.semester}";`,
        `    std::string email = "${email}";`,
        '',
        '    std::string officeHours() {',
        `        return "${officeHours}";`,
        '    }',
        '};',
      ].join('\n');
    case 'javascript':
    case 'typescript':
      return [
        'class TeachingAssistant {',
        `  name = "${name}";`,
        `  course = "${course.name}";`,
        `  semester = "${course.semester}";`,
        `  email = "${email}";`,
        '',
        '  officeHours() {',
        `    return "${officeHours}";`,
        '  }',
        '}',
      ].join('\n');
    default:
      return [
        'TeachingAssistant {',
        `  name: "${name}"`,
        `  course: "${course.name}"`,
        `  semester: "${course.semester}"`,
        `  email: "${email}"`,
        `  officeHours: "${officeHours}"`,
        '}',
      ].join('\n');
  }
}

// ---------------------------------------------------------------------------
// Tokenizer for the card above. Just enough to tint strings, keywords and the
// class name — the snippet is generated by us, so there is no need for a real
// parser, and a lexer that only ever sees these ten lines can stay this dumb.
// ---------------------------------------------------------------------------

export type TokenKind = 'kw' | 'str' | 'type' | 'plain';

export interface SnippetToken {
  text: string;
  kind: TokenKind;
}

// Quoted strings, then the type names we emit, then keywords. Order matters
// inside each group only in that `std::string` has to beat `string`.
const TOKEN_RE =
  /("(?:[^"\\]|\\.)*")|\b(TeachingAssistant|std::string|String|string)\b|\b(class|public|private|def|return|new|const|let|var|void|self|this)\b/g;

export function tokenizeSnippet(code: string): SnippetToken[] {
  const tokens: SnippetToken[] = [];
  let last = 0;

  for (const m of code.matchAll(TOKEN_RE)) {
    const start = m.index;
    if (start > last) tokens.push({ text: code.slice(last, start), kind: 'plain' });

    const [text, str, type] = m;
    tokens.push({ text, kind: str ? 'str' : type ? 'type' : 'kw' });
    last = start + text.length;
  }

  if (last < code.length) tokens.push({ text: code.slice(last), kind: 'plain' });
  return tokens;
}

/** Filename shown on the code card's tab, e.g. `TeachingAssistant.java`. */
export function snippetFilename(): string {
  switch (content.course.language.toLowerCase()) {
    case 'python':
      return 'teaching_assistant.py';
    case 'java':
      return 'TeachingAssistant.java';
    case 'cpp':
    case 'c++':
      return 'teaching_assistant.cpp';
    case 'javascript':
      return 'teachingAssistant.js';
    case 'typescript':
      return 'teachingAssistant.ts';
    default:
      return 'teaching-assistant.txt';
  }
}
